### ISSUE TITLE
Delete this repository

### ISSUE THREAD

**Issue by sourcedelica** [actor-framework/conan#10]
A while back I started using https://github.com/bincrafters/conan-caf as the primary repository for the CAF Conan recipe.  Bincrafters is a collective of developers writing Conan package recipes for the major C/C++ libraries.  The Bincrafters CAF recipe has been accepted into the premier Conan package repository called [Conan Center](https://bintray.com/conan/conan-center) (search for `caf`), and we Bincrafters keep it up to date with new releases of CAF.

Because it has diverged so much I propose to delete this repository and add a reference to [conan-caf](https://github.com/bincrafters/conan-caf) on the main actor-framework `README.md`.

**Comment by Neverlord** [comment]
Thanks for the heads-up! I think I'll gladly remove this repository.

> add a reference to conan-caf on the main actor-framework README.md.

Would you mind making a PR to the readme with the necessary conan steps? :)

**Comment by sourcedelica** [comment]
I submitted the PR
